services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    environment:
      - PROMETHEUS_SOURCE_FILE_PATH=/home/dickson/social-lab/social-jwt/prometheus/prometheus.yml
    volumes:
      - prometheus-data:/prometheus
      - /home/dickson/social-lab/social-jwt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  prometheus-data: {}
  grafana-data: {}
