pipeline {
   agent any
   tools {
      maven '3.9.5'
      jdk 'jdk-20'
    }
       
   environment {

    DOCKER_NAME = 'testingf'
    JDK_HOME = tool 'jdk-20'
    DOCKER_CREDENTIALS = credentials('dockerhub')
      
  }
  stages {

    stage("clone Repository") {
      steps {
          checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/elitekaycy/social-lab']])
       }
    }

    stage("CD WORKDIR") { 
        steps {
            dir('testingf/testing') {
              script {
                    env.WORKDIR = pwd()
                }
            }
          }
    }
   

    stage("build image") {
      steps {
        dir(env.WORKDIR) {
           script {
             sh 'docker build -t ${DOCKER_NAME}:latest .'
          }
       } 
      } 
    }
    

   stage("push to docker hub") {

      steps {
           
        script {

           withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'pwd', usernameVariable: 'username')]) {
                 sh "echo ${pwd} | docker login -u ${username} --password-stdin"
                 sh "docker push ${DOCKER_NAME}:latest"

           }

    }
  } 
   }

  }

  post {
        always {
            sh 'docker logout'
            cleanWs()
        }
    }
}
