global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: "social-jwt"
    metrics_path: /actuator/prometheus
    honor_labels: false
    honor_timestamps: true
    scheme: http
    static_configs:
      - targets:
          - "172.19.26.74:8080"
